# Categories (group-title values) to exclude entirely.
# Matched exactly (case-sensitive) against each channel's group-title
# attribute -- unlike exclude_list.py's channel-name substring matching.
CATEGORY_EXCLUDE_LIST = [
    "Live Events",
    "Dansk reality & underholdning",
    "Svensk reality och underhållning",
    "Big Brother Live",
    "Sport",
    "Det beste fra MTV",
    "Det bästa från MTV",
    "Living",
    "Dokumentärer",
    "Dokumentarer",
    "Det bedste fra MTV",
    "Documentary + Science",
    "Animals + Nature",
    "Barn",
    "Competition Reality",
    "Sports Presented By Capital One",
    "Kids en Français",
    "News + Opinion",
    "For børn",
    "For barn",
    "History + Science",
    "Home + Food",
    "Mat & livsstil",
    "Mad & livsstil",
    "Music Videos",
    "Talkshow",
    "Realityserier",
    "Ambiance",
    "LocalNow🇺🇸: Nature and Outdoors",
    "LocalNow🇺🇸: My City",
    "LocalNow🇺🇸: Family and Faith",
    "LocalNow🇺🇸: Music and Arts",
    "Sports",
    "News",
    "Music",
    "Combat Sports",
    "Motor Sports",
    "Sports & Outdoors",
    "Sports On Now",
    "Local News",
    "National News",
    "Latino",
    "House/Garden",
    "Lifestyle",
    "Westerns",
    "Animals",
    "Animals & Nature",
    "Anime",
    "Anime & Gaming",
    "Auction",
    "Automotive",
    "Environment",
    "En Español",
    "Game Show",
    "Game Shows",
    "Auto & Motorsports",
    "Kids",
    "Family & Kids",
    "News & Opinion",
    "Talk Show & Music",
    "Reality",
    "Biography",
    "Cars & Racing",
    "Documentary",
    "Documentaries",
    "Food",
    "Good Eats",
    "Health",
    "Noticias",
    "Faith & Family",
    "Faith & Inspiration",
    "History & Adventure",
    "History & Learning",
    "Cooking",
    "Daytime + Game Shows",
    "Home & Design",
    "Home & Food",
    "Home",
    "Reality",
    "Reality Competition",
    "Science & Nature",
    "Romance",
    "Pop Culture",
    "Travel & Food",
    "Travel & Lifestyle",
    "Travel & Outdoors",
    "Reality TV",
    "LocalNow🇺🇸: Sports",
    "Children-Music",
    "Music & Radio",
    "Games & Competition",
    "Gameshows & Competition",
    "Nature, History & Science",
    "LocalNow🇺🇸: News And Opinion",
    "LocalNow🇺🇸: More Cities",
    "LocalNow🇺🇸: En Espanol",
    "Lifestyle & Pop Culture",
    "Black Entertainment",
]
