# Categories (group-title values) to exclude entirely.
# Matched exactly (case-sensitive) against each channel's group-title
# attribute -- unlike exclude_list.py's channel-name substring matching.
CATEGORY_EXCLUDE_LIST = [
    "Sports",
    "News",
    "Music",
    "Combat Sports",
    "Motor Sports",
    "Sports & Outdoors",
    "Sports On Now",
    "Local News",
    "National News",
    "Latino",
    "House/Garden",
    "Lifestyle",
    "Westerns",
    "Animals",
    "Animals & Nature",
    "Anime",
    "Anime & Gaming",
    "Auction",
    "Automotive",
    "Environment",
    "En Español",
    "Game Show",
    "Game Shows",
    "Auto & Motorsports",
    "Kids",
    "Family & Kids",
    "News & Opinion",
    "Talk Show & Music",
    "Reality",
    "Biography",
    "Cars & Racing",
    "Documentary",
    "Documentaries",
    "Food",
    "Good Eats",
    "Health",
    "Noticias",
    "Faith & Family",
    "Faith & Inspiration",
    "History & Adventure",
    "History & Learning",
    "Cooking",
    "Daytime + Game Shows",
    "Home & Design",
    "Home & Food",
    "Home",
    "Reality",
    "Reality Competition",
    "Science & Nature",
    "Romance",
    "Pop Culture",
    "Travel & Food",
    "Travel & Lifestyle",
    "Travel & Outdoors",
]
