- name: changed files
  id: files
  run: |
    ANY_CHANGED=false
    # For PRs, use github.event.pull_request.base.ref
    # For push events, use the previous commit
    if [ "${{ github.event_name }}" = "pull_request" ]; then
      BASE_REF="${{ github.event.pull_request.base.ref }}"
      git fetch origin $BASE_REF
      ALL_CHANGED_FILES=$(git diff --name-only origin/$BASE_REF -- streams/ | tr '\n' ' ')
    else
      # For push events or workflow_dispatch
      ALL_CHANGED_FILES=$(git diff --name-only HEAD^ -- streams/ | tr '\n' ' ')
    fi
    
    if [ -n "${ALL_CHANGED_FILES}" ]; then
      ANY_CHANGED=true
    fi
    echo "all_changed_files=$ALL_CHANGED_FILES" >> "$GITHUB_OUTPUT"
    echo "any_changed=$ANY_CHANGED" >> "$GITHUB_OUTPUT"
