name: update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: setup git
        run: |
          git config user.name "iptv-bot[bot]"
          git config user.email "84861620+iptv-bot[bot]@users.noreply.github.com"
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: install dependencies
        run: npm install
      
      - name: update internal playlists
        run: npm run playlist:update --silent >> $GITHUB_OUTPUT
        id: playlist-update
      
      - name: check internal playlists
        run: |
          npm run playlist:lint
          npm run playlist:validate
      
      - name: generate public playlists
        run: npm run playlist:generate
      
      - name: generate .api/streams.json
        run: npm run api:generate
      
      - name: update readme
        run: npm run readme:update
      
      - run: git status
      
      - name: commit changes to /streams
        run: |
          git add streams
          git status
          git commit --allow-empty -m "[Bot] Update /streams" -m "Committed via [update](https://github.com/iptv-org/iptv/actions/runs/${{ github.run_id }}) workflow." -m "${{ steps.playlist-update.outputs.OUTPUT }}" --no-verify
      
      - name: commit changes to playlists.md
        run: |
          git add PLAYLISTS.md
          git status
          git commit --allow-empty -m "[Bot] Update PLAYLISTS.md" -m "Committed via [update](https://github.com/iptv-org/iptv/actions/runs/${{ github.run_id }}) workflow." --no-verify
      
      - name: push all changes to the repository
        if: github.ref == 'refs/heads/master'
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
